name: Validate

on:
  push:
  pull_request:

jobs:
#  validate_hacs:
#    runs-on: "ubuntu-latest"
#    steps:
#      - uses: "actions/checkout@v2"
#      - name: HACS validation
#        uses: "hacs/action@main"
#        with:
#          category: "plugin"
  validate_hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
